version: '3'

services:
  postgres:
    #   Use the Docker Image postgres. This will pull the newest release.
    image: postgres:11.1-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'db_licence_service'
    volumes:
      - ./init:/docker-entrypoint-initdb.d/

volumes:
  database_data:
    driver: local
