trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'
  imageName: 'injectit'
steps:
  - task: GoTool@0
    inputs:
      version: '1.13.5'
  - task: Go@0
    inputs:
      command: 'get'
      arguments: '-t -v ./...'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
  - task: Go@0
    inputs:
      command: 'build '
      arguments: '-v ./...'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
  - task: CopyFiles@2
    inputs:
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: drop
  - task: Docker@2
    displayName: Build and push an image to container registry
    inputs:
      command: buildAndPush
      repository: 'injectit/organization'
      dockerfile: '**/Dockerfile'
      containerRegistry: 'InjectIT'
      tags: |
        $(Build.BuildId)
        latest