// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	grpc "github.com/go-kit/kit/transport/grpc"
	endpoint "github.com/lukaszozimek/organization_service/pkg/endpoint"
	pb "github.com/lukaszozimek/organization_service/pkg/grpc/pb"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	createUserOrganizationById grpc.Handler
	deleteUserOrganizationById grpc.Handler
	getUserOrganizationById    grpc.Handler
	getUserOrganizations       grpc.Handler
	updateUserOrganizationById grpc.Handler
	health                     grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.OrganizationServer {
	return &grpcServer{
		createUserOrganizationById: makeCreateUserOrganizationByIdHandler(endpoints, options["CreateUserOrganizationById"]),
		deleteUserOrganizationById: makeDeleteUserOrganizationByIdHandler(endpoints, options["DeleteUserOrganizationById"]),
		getUserOrganizationById:    makeGetUserOrganizationByIdHandler(endpoints, options["GetUserOrganizationById"]),
		getUserOrganizations:       makeGetUserOrganizationsHandler(endpoints, options["GetUserOrganizations"]),
		health:                     makeHealthHandler(endpoints, options["Health"]),
		updateUserOrganizationById: makeUpdateUserOrganizationByIdHandler(endpoints, options["UpdateUserOrganizationById"]),
	}
}
