// Code generated by protoc-gen-go. DO NOT EDIT.
// source: organization/pkg/grpc/pb/organization.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUserOrganizationByIdRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserOrganizationByIdRequest) Reset()         { *m = CreateUserOrganizationByIdRequest{} }
func (m *CreateUserOrganizationByIdRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserOrganizationByIdRequest) ProtoMessage()    {}
func (*CreateUserOrganizationByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e871b367ab5be44b, []int{0}
}

func (m *CreateUserOrganizationByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserOrganizationByIdRequest.Unmarshal(m, b)
}
func (m *CreateUserOrganizationByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserOrganizationByIdRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserOrganizationByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserOrganizationByIdRequest.Merge(m, src)
}
func (m *CreateUserOrganizationByIdRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserOrganizationByIdRequest.Size(m)
}
func (m *CreateUserOrganizationByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserOrganizationByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserOrganizationByIdRequest proto.InternalMessageInfo

type CreateUserOrganizationByIdReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserOrganizationByIdReply) Reset()         { *m = CreateUserOrganizationByIdReply{} }
func (m *CreateUserOrganizationByIdReply) String() string { return proto.CompactTextString(m) }
func (*CreateUserOrganizationByIdReply) ProtoMessage()    {}
func (*CreateUserOrganizationByIdReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e871b367ab5be44b, []int{1}
}

func (m *CreateUserOrganizationByIdReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserOrganizationByIdReply.Unmarshal(m, b)
}
func (m *CreateUserOrganizationByIdReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserOrganizationByIdReply.Marshal(b, m, deterministic)
}
func (m *CreateUserOrganizationByIdReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserOrganizationByIdReply.Merge(m, src)
}
func (m *CreateUserOrganizationByIdReply) XXX_Size() int {
	return xxx_messageInfo_CreateUserOrganizationByIdReply.Size(m)
}
func (m *CreateUserOrganizationByIdReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserOrganizationByIdReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserOrganizationByIdReply proto.InternalMessageInfo

type DeleteUserOrganizationByIdRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserOrganizationByIdRequest) Reset()         { *m = DeleteUserOrganizationByIdRequest{} }
func (m *DeleteUserOrganizationByIdRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserOrganizationByIdRequest) ProtoMessage()    {}
func (*DeleteUserOrganizationByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e871b367ab5be44b, []int{2}
}

func (m *DeleteUserOrganizationByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserOrganizationByIdRequest.Unmarshal(m, b)
}
func (m *DeleteUserOrganizationByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserOrganizationByIdRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserOrganizationByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserOrganizationByIdRequest.Merge(m, src)
}
func (m *DeleteUserOrganizationByIdRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserOrganizationByIdRequest.Size(m)
}
func (m *DeleteUserOrganizationByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserOrganizationByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserOrganizationByIdRequest proto.InternalMessageInfo

type DeleteUserOrganizationByIdReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserOrganizationByIdReply) Reset()         { *m = DeleteUserOrganizationByIdReply{} }
func (m *DeleteUserOrganizationByIdReply) String() string { return proto.CompactTextString(m) }
func (*DeleteUserOrganizationByIdReply) ProtoMessage()    {}
func (*DeleteUserOrganizationByIdReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e871b367ab5be44b, []int{3}
}

func (m *DeleteUserOrganizationByIdReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserOrganizationByIdReply.Unmarshal(m, b)
}
func (m *DeleteUserOrganizationByIdReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserOrganizationByIdReply.Marshal(b, m, deterministic)
}
func (m *DeleteUserOrganizationByIdReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserOrganizationByIdReply.Merge(m, src)
}
func (m *DeleteUserOrganizationByIdReply) XXX_Size() int {
	return xxx_messageInfo_DeleteUserOrganizationByIdReply.Size(m)
}
func (m *DeleteUserOrganizationByIdReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserOrganizationByIdReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserOrganizationByIdReply proto.InternalMessageInfo

type GetUserOrganizationByIdRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserOrganizationByIdRequest) Reset()         { *m = GetUserOrganizationByIdRequest{} }
func (m *GetUserOrganizationByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserOrganizationByIdRequest) ProtoMessage()    {}
func (*GetUserOrganizationByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e871b367ab5be44b, []int{4}
}

func (m *GetUserOrganizationByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserOrganizationByIdRequest.Unmarshal(m, b)
}
func (m *GetUserOrganizationByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserOrganizationByIdRequest.Marshal(b, m, deterministic)
}
func (m *GetUserOrganizationByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserOrganizationByIdRequest.Merge(m, src)
}
func (m *GetUserOrganizationByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserOrganizationByIdRequest.Size(m)
}
func (m *GetUserOrganizationByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserOrganizationByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserOrganizationByIdRequest proto.InternalMessageInfo

type GetUserOrganizationByIdReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserOrganizationByIdReply) Reset()         { *m = GetUserOrganizationByIdReply{} }
func (m *GetUserOrganizationByIdReply) String() string { return proto.CompactTextString(m) }
func (*GetUserOrganizationByIdReply) ProtoMessage()    {}
func (*GetUserOrganizationByIdReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e871b367ab5be44b, []int{5}
}

func (m *GetUserOrganizationByIdReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserOrganizationByIdReply.Unmarshal(m, b)
}
func (m *GetUserOrganizationByIdReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserOrganizationByIdReply.Marshal(b, m, deterministic)
}
func (m *GetUserOrganizationByIdReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserOrganizationByIdReply.Merge(m, src)
}
func (m *GetUserOrganizationByIdReply) XXX_Size() int {
	return xxx_messageInfo_GetUserOrganizationByIdReply.Size(m)
}
func (m *GetUserOrganizationByIdReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserOrganizationByIdReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserOrganizationByIdReply proto.InternalMessageInfo

type GetUserOrganizationsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserOrganizationsRequest) Reset()         { *m = GetUserOrganizationsRequest{} }
func (m *GetUserOrganizationsRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserOrganizationsRequest) ProtoMessage()    {}
func (*GetUserOrganizationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e871b367ab5be44b, []int{6}
}

func (m *GetUserOrganizationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserOrganizationsRequest.Unmarshal(m, b)
}
func (m *GetUserOrganizationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserOrganizationsRequest.Marshal(b, m, deterministic)
}
func (m *GetUserOrganizationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserOrganizationsRequest.Merge(m, src)
}
func (m *GetUserOrganizationsRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserOrganizationsRequest.Size(m)
}
func (m *GetUserOrganizationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserOrganizationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserOrganizationsRequest proto.InternalMessageInfo

type GetUserOrganizationsReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserOrganizationsReply) Reset()         { *m = GetUserOrganizationsReply{} }
func (m *GetUserOrganizationsReply) String() string { return proto.CompactTextString(m) }
func (*GetUserOrganizationsReply) ProtoMessage()    {}
func (*GetUserOrganizationsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e871b367ab5be44b, []int{7}
}

func (m *GetUserOrganizationsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserOrganizationsReply.Unmarshal(m, b)
}
func (m *GetUserOrganizationsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserOrganizationsReply.Marshal(b, m, deterministic)
}
func (m *GetUserOrganizationsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserOrganizationsReply.Merge(m, src)
}
func (m *GetUserOrganizationsReply) XXX_Size() int {
	return xxx_messageInfo_GetUserOrganizationsReply.Size(m)
}
func (m *GetUserOrganizationsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserOrganizationsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserOrganizationsReply proto.InternalMessageInfo

type UpdateUserOrganizationByIdRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserOrganizationByIdRequest) Reset()         { *m = UpdateUserOrganizationByIdRequest{} }
func (m *UpdateUserOrganizationByIdRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserOrganizationByIdRequest) ProtoMessage()    {}
func (*UpdateUserOrganizationByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e871b367ab5be44b, []int{8}
}

func (m *UpdateUserOrganizationByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserOrganizationByIdRequest.Unmarshal(m, b)
}
func (m *UpdateUserOrganizationByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserOrganizationByIdRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserOrganizationByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserOrganizationByIdRequest.Merge(m, src)
}
func (m *UpdateUserOrganizationByIdRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserOrganizationByIdRequest.Size(m)
}
func (m *UpdateUserOrganizationByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserOrganizationByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserOrganizationByIdRequest proto.InternalMessageInfo

type UpdateUserOrganizationByIdReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserOrganizationByIdReply) Reset()         { *m = UpdateUserOrganizationByIdReply{} }
func (m *UpdateUserOrganizationByIdReply) String() string { return proto.CompactTextString(m) }
func (*UpdateUserOrganizationByIdReply) ProtoMessage()    {}
func (*UpdateUserOrganizationByIdReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e871b367ab5be44b, []int{9}
}

func (m *UpdateUserOrganizationByIdReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserOrganizationByIdReply.Unmarshal(m, b)
}
func (m *UpdateUserOrganizationByIdReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserOrganizationByIdReply.Marshal(b, m, deterministic)
}
func (m *UpdateUserOrganizationByIdReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserOrganizationByIdReply.Merge(m, src)
}
func (m *UpdateUserOrganizationByIdReply) XXX_Size() int {
	return xxx_messageInfo_UpdateUserOrganizationByIdReply.Size(m)
}
func (m *UpdateUserOrganizationByIdReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserOrganizationByIdReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserOrganizationByIdReply proto.InternalMessageInfo

type HealthRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthRequest) Reset()         { *m = HealthRequest{} }
func (m *HealthRequest) String() string { return proto.CompactTextString(m) }
func (*HealthRequest) ProtoMessage()    {}
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e871b367ab5be44b, []int{10}
}

func (m *HealthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthRequest.Unmarshal(m, b)
}
func (m *HealthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthRequest.Marshal(b, m, deterministic)
}
func (m *HealthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthRequest.Merge(m, src)
}
func (m *HealthRequest) XXX_Size() int {
	return xxx_messageInfo_HealthRequest.Size(m)
}
func (m *HealthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthRequest proto.InternalMessageInfo

type HealthReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthReply) Reset()         { *m = HealthReply{} }
func (m *HealthReply) String() string { return proto.CompactTextString(m) }
func (*HealthReply) ProtoMessage()    {}
func (*HealthReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e871b367ab5be44b, []int{11}
}

func (m *HealthReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthReply.Unmarshal(m, b)
}
func (m *HealthReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthReply.Marshal(b, m, deterministic)
}
func (m *HealthReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthReply.Merge(m, src)
}
func (m *HealthReply) XXX_Size() int {
	return xxx_messageInfo_HealthReply.Size(m)
}
func (m *HealthReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthReply.DiscardUnknown(m)
}

var xxx_messageInfo_HealthReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateUserOrganizationByIdRequest)(nil), "pb.CreateUserOrganizationByIdRequest")
	proto.RegisterType((*CreateUserOrganizationByIdReply)(nil), "pb.CreateUserOrganizationByIdReply")
	proto.RegisterType((*DeleteUserOrganizationByIdRequest)(nil), "pb.DeleteUserOrganizationByIdRequest")
	proto.RegisterType((*DeleteUserOrganizationByIdReply)(nil), "pb.DeleteUserOrganizationByIdReply")
	proto.RegisterType((*GetUserOrganizationByIdRequest)(nil), "pb.GetUserOrganizationByIdRequest")
	proto.RegisterType((*GetUserOrganizationByIdReply)(nil), "pb.GetUserOrganizationByIdReply")
	proto.RegisterType((*GetUserOrganizationsRequest)(nil), "pb.GetUserOrganizationsRequest")
	proto.RegisterType((*GetUserOrganizationsReply)(nil), "pb.GetUserOrganizationsReply")
	proto.RegisterType((*UpdateUserOrganizationByIdRequest)(nil), "pb.UpdateUserOrganizationByIdRequest")
	proto.RegisterType((*UpdateUserOrganizationByIdReply)(nil), "pb.UpdateUserOrganizationByIdReply")
	proto.RegisterType((*HealthRequest)(nil), "pb.HealthRequest")
	proto.RegisterType((*HealthReply)(nil), "pb.HealthReply")
}

func init() {
	proto.RegisterFile("organization/pkg/grpc/pb/organization.proto", fileDescriptor_e871b367ab5be44b)
}

var fileDescriptor_e871b367ab5be44b = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x41, 0xa4, 0x87, 0xd1, 0x52, 0x5c, 0x04, 0x71, 0x6b, 0xff, 0xa5, 0x78, 0x52, 0x12,
	0xd0, 0x6f, 0xa0, 0x82, 0x7a, 0x12, 0x84, 0x7a, 0x95, 0xc4, 0x0e, 0x69, 0x71, 0x69, 0xc6, 0xcd,
	0x7a, 0x58, 0xbf, 0x96, 0x5f, 0x50, 0xd6, 0x4d, 0x20, 0x85, 0xec, 0xce, 0x75, 0xe7, 0x37, 0x6f,
	0xc8, 0x7b, 0x2f, 0x70, 0x55, 0xe9, 0x32, 0xdf, 0x6d, 0x7f, 0x72, 0xb3, 0xad, 0x76, 0x19, 0x7d,
	0x96, 0x59, 0xa9, 0xe9, 0x23, 0xa3, 0x22, 0xeb, 0x0e, 0x52, 0xd2, 0x95, 0xa9, 0xc4, 0x01, 0x15,
	0xc9, 0x12, 0x16, 0xf7, 0x1a, 0x73, 0x83, 0xab, 0x1a, 0xf5, 0x4b, 0x87, 0xb9, 0xb3, 0xcf, 0xeb,
	0x57, 0xfc, 0xfa, 0xc6, 0xda, 0x24, 0x0b, 0x98, 0xc5, 0x20, 0x52, 0xd6, 0xe9, 0x3c, 0xa0, 0x42,
	0x56, 0x27, 0x06, 0x39, 0x9d, 0x39, 0x4c, 0x1f, 0xd1, 0xc4, 0x44, 0xa6, 0x70, 0x11, 0x24, 0x9c,
	0xc2, 0x04, 0xc6, 0x3d, 0xf3, 0xba, 0x5d, 0x1f, 0xc3, 0x79, 0xff, 0xb8, 0xf9, 0x8a, 0x15, 0xad,
	0x79, 0x37, 0x62, 0x90, 0xd3, 0x19, 0xc1, 0xf0, 0x09, 0x73, 0x65, 0x36, 0xed, 0xce, 0x10, 0x8e,
	0xda, 0x07, 0x52, 0xf6, 0xe6, 0xf7, 0x10, 0x8e, 0xbb, 0x9b, 0x62, 0x03, 0x32, 0xec, 0xb0, 0xb8,
	0x4c, 0xa9, 0x48, 0xd9, 0x98, 0xe4, 0x92, 0xc3, 0x48, 0x59, 0x77, 0x29, 0x9c, 0x81, 0xbf, 0xc4,
	0x06, 0xe9, 0x2f, 0x31, 0x51, 0x8a, 0x77, 0x38, 0x0b, 0x04, 0x25, 0x12, 0xb7, 0x1f, 0xcf, 0x59,
	0xce, 0xa3, 0x8c, 0x3b, 0xf0, 0x06, 0xa7, 0x7d, 0x51, 0x8a, 0x59, 0x60, 0xb3, 0xed, 0x80, 0x9c,
	0x84, 0x81, 0xc6, 0xa2, 0x70, 0xc0, 0xde, 0x22, 0xb6, 0x25, 0xde, 0x22, 0xa6, 0x27, 0xe2, 0x1a,
	0x06, 0xbe, 0x16, 0xe2, 0xc4, 0xe1, 0x7b, 0x9d, 0x91, 0xa3, 0xee, 0x13, 0x29, 0x5b, 0x0c, 0xfe,
	0x7f, 0xdb, 0xdb, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x70, 0x0b, 0xe9, 0xe5, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrganizationClient is the client API for Organization service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrganizationClient interface {
	CreateUserOrganizationById(ctx context.Context, in *CreateUserOrganizationByIdRequest, opts ...grpc.CallOption) (*CreateUserOrganizationByIdReply, error)
	DeleteUserOrganizationById(ctx context.Context, in *DeleteUserOrganizationByIdRequest, opts ...grpc.CallOption) (*DeleteUserOrganizationByIdReply, error)
	GetUserOrganizationById(ctx context.Context, in *GetUserOrganizationByIdRequest, opts ...grpc.CallOption) (*GetUserOrganizationByIdReply, error)
	GetUserOrganizations(ctx context.Context, in *GetUserOrganizationsRequest, opts ...grpc.CallOption) (*GetUserOrganizationsReply, error)
	UpdateUserOrganizationById(ctx context.Context, in *UpdateUserOrganizationByIdRequest, opts ...grpc.CallOption) (*UpdateUserOrganizationByIdReply, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthReply, error)
}

type organizationClient struct {
	cc *grpc.ClientConn
}

func NewOrganizationClient(cc *grpc.ClientConn) OrganizationClient {
	return &organizationClient{cc}
}

func (c *organizationClient) CreateUserOrganizationById(ctx context.Context, in *CreateUserOrganizationByIdRequest, opts ...grpc.CallOption) (*CreateUserOrganizationByIdReply, error) {
	out := new(CreateUserOrganizationByIdReply)
	err := c.cc.Invoke(ctx, "/pb.Organization/CreateUserOrganizationById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationClient) DeleteUserOrganizationById(ctx context.Context, in *DeleteUserOrganizationByIdRequest, opts ...grpc.CallOption) (*DeleteUserOrganizationByIdReply, error) {
	out := new(DeleteUserOrganizationByIdReply)
	err := c.cc.Invoke(ctx, "/pb.Organization/DeleteUserOrganizationById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationClient) GetUserOrganizationById(ctx context.Context, in *GetUserOrganizationByIdRequest, opts ...grpc.CallOption) (*GetUserOrganizationByIdReply, error) {
	out := new(GetUserOrganizationByIdReply)
	err := c.cc.Invoke(ctx, "/pb.Organization/GetUserOrganizationById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationClient) GetUserOrganizations(ctx context.Context, in *GetUserOrganizationsRequest, opts ...grpc.CallOption) (*GetUserOrganizationsReply, error) {
	out := new(GetUserOrganizationsReply)
	err := c.cc.Invoke(ctx, "/pb.Organization/GetUserOrganizations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationClient) UpdateUserOrganizationById(ctx context.Context, in *UpdateUserOrganizationByIdRequest, opts ...grpc.CallOption) (*UpdateUserOrganizationByIdReply, error) {
	out := new(UpdateUserOrganizationByIdReply)
	err := c.cc.Invoke(ctx, "/pb.Organization/UpdateUserOrganizationById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthReply, error) {
	out := new(HealthReply)
	err := c.cc.Invoke(ctx, "/pb.Organization/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrganizationServer is the server API for Organization service.
type OrganizationServer interface {
	CreateUserOrganizationById(context.Context, *CreateUserOrganizationByIdRequest) (*CreateUserOrganizationByIdReply, error)
	DeleteUserOrganizationById(context.Context, *DeleteUserOrganizationByIdRequest) (*DeleteUserOrganizationByIdReply, error)
	GetUserOrganizationById(context.Context, *GetUserOrganizationByIdRequest) (*GetUserOrganizationByIdReply, error)
	GetUserOrganizations(context.Context, *GetUserOrganizationsRequest) (*GetUserOrganizationsReply, error)
	UpdateUserOrganizationById(context.Context, *UpdateUserOrganizationByIdRequest) (*UpdateUserOrganizationByIdReply, error)
	Health(context.Context, *HealthRequest) (*HealthReply, error)
}

// UnimplementedOrganizationServer can be embedded to have forward compatible implementations.
type UnimplementedOrganizationServer struct {
}

func (*UnimplementedOrganizationServer) CreateUserOrganizationById(ctx context.Context, req *CreateUserOrganizationByIdRequest) (*CreateUserOrganizationByIdReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserOrganizationById not implemented")
}
func (*UnimplementedOrganizationServer) DeleteUserOrganizationById(ctx context.Context, req *DeleteUserOrganizationByIdRequest) (*DeleteUserOrganizationByIdReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserOrganizationById not implemented")
}
func (*UnimplementedOrganizationServer) GetUserOrganizationById(ctx context.Context, req *GetUserOrganizationByIdRequest) (*GetUserOrganizationByIdReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserOrganizationById not implemented")
}
func (*UnimplementedOrganizationServer) GetUserOrganizations(ctx context.Context, req *GetUserOrganizationsRequest) (*GetUserOrganizationsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserOrganizations not implemented")
}
func (*UnimplementedOrganizationServer) UpdateUserOrganizationById(ctx context.Context, req *UpdateUserOrganizationByIdRequest) (*UpdateUserOrganizationByIdReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserOrganizationById not implemented")
}
func (*UnimplementedOrganizationServer) Health(ctx context.Context, req *HealthRequest) (*HealthReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}

func RegisterOrganizationServer(s *grpc.Server, srv OrganizationServer) {
	s.RegisterService(&_Organization_serviceDesc, srv)
}

func _Organization_CreateUserOrganizationById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserOrganizationByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServer).CreateUserOrganizationById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Organization/CreateUserOrganizationById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServer).CreateUserOrganizationById(ctx, req.(*CreateUserOrganizationByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Organization_DeleteUserOrganizationById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserOrganizationByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServer).DeleteUserOrganizationById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Organization/DeleteUserOrganizationById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServer).DeleteUserOrganizationById(ctx, req.(*DeleteUserOrganizationByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Organization_GetUserOrganizationById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserOrganizationByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServer).GetUserOrganizationById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Organization/GetUserOrganizationById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServer).GetUserOrganizationById(ctx, req.(*GetUserOrganizationByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Organization_GetUserOrganizations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserOrganizationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServer).GetUserOrganizations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Organization/GetUserOrganizations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServer).GetUserOrganizations(ctx, req.(*GetUserOrganizationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Organization_UpdateUserOrganizationById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserOrganizationByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServer).UpdateUserOrganizationById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Organization/UpdateUserOrganizationById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServer).UpdateUserOrganizationById(ctx, req.(*UpdateUserOrganizationByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Organization_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Organization/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Organization_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Organization",
	HandlerType: (*OrganizationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUserOrganizationById",
			Handler:    _Organization_CreateUserOrganizationById_Handler,
		},
		{
			MethodName: "DeleteUserOrganizationById",
			Handler:    _Organization_DeleteUserOrganizationById_Handler,
		},
		{
			MethodName: "GetUserOrganizationById",
			Handler:    _Organization_GetUserOrganizationById_Handler,
		},
		{
			MethodName: "GetUserOrganizations",
			Handler:    _Organization_GetUserOrganizations_Handler,
		},
		{
			MethodName: "UpdateUserOrganizationById",
			Handler:    _Organization_UpdateUserOrganizationById_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Organization_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "organization/pkg/grpc/pb/organization.proto",
}
